sonar.projectKey=kazuyaTakahashi1988_react-native-expo
sonar.organization=kazuyatakahashi1988
sonar.sources=app,stories,.storybook,index.ts,vitest.config.ts,vitest.shims.d.ts
sonar.exclusions=**/node_modules/**,**/.expo/**,**/ios/**,**/android/**
sonar.typescript.tsconfigPaths=tsconfig.sonar.json
sonar.sourceEncoding=UTF-8
